#!/usr/bin/python

    # Enumerates possible attack vectors
atomic_purple_attacks = {
    # "Boot or Logon Autostart Execution": "ID:T1547",
    "Brute Force": "ID:1110",
    # "Phishing": "ID:T1660",
    # "Impair Defenses": "ID:T1562",
}

    # Enumerates defense possibilities for various attacks
atomic_purple_defense = {
    # "M1047 Audit: Routinely check account role permissions to ensure only expected users and roles have permission to modify defensive tools and settings.",
    # "M1038 Execution Prevention: Use application control where appropriate, especially regarding the execution of tools outside of the organization's security policies (such as rootkit removal tools) that have been abused to impair system defenses. Ensure that only approved security applications are used and running on enterprise systems.",
    # "M1022 Restrict File and Directory Permissions: Ensure proper process and file permissions are in place to prevent adversaries from disabling or interfering with security/logging services.",
    # "M1024 Restrict Registry Permissions: Ensure proper Registry permissions are in place to prevent adversaries from disabling or interfering with security/logging services.",
    # "M1054 Software Configuration: Consider implementing policies on internal web servers, such HTTP Strict Transport Security, that enforce the use of HTTPS/network traffic encryption to prevent insecure connections.",
    # "M1018 User Account Management: Ensure proper user permissions are in place to prevent adversaries from disabling or interfering with security/logging services.",
}

    
    
